# GitLab pipeline to build, test and release this Telegram bot.
image: quay.io/buildah/stable

stages:
  - build

# Instructions inspired by https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-alternatives
build-amd64:
  stage: build
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
    IMAGE_LATEST: "${CI_REGISTRY_IMAGE}:latest"
  before_script:
    - export REGISTRY_AUTH_FILE=${HOME}/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah build -t $IMAGE_NAME -t $IMAGE_LATEST
    - buildah push $IMAGE_NAME
    - buildah push $IMAGE_LATEST

build-arm64v7:
  stage: build
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/arm64v8:${CI_COMMIT_SHORT_SHA}"
    IMAGE_LATEST: "${CI_REGISTRY_IMAGE}:latest"
  before_script:
    - export REGISTRY_AUTH_FILE=${HOME}/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah build -t $IMAGE_NAME -t $IMAGE_LATEST -f Dockerfile.arm32v7
    - buildah push $IMAGE_NAME
    - buildah push $IMAGE_LATEST
