# GitLab pipeline to build, test and release this Telegram bot.
image: quay.io/buildah/stable

stages:
  - build

# Instructions inspired by https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-alternatives
build-amd64:
  stage: build
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/antispam-sapienza-bot:${CI_COMMIT_SHORT_SHA}"
  before_script:
    - export REGISTRY_AUTH_FILE=${HOME}/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah images
    - buildah built -t $IMAGE_NAME
    - buildah images
    - buildah push $IMAGE_NAME
