# GitLab pipeline to build, test and release this Telegram bot.
image: golang:1.16

stages:
  - build
  - test
  - release

variables:
  # We need to move GOPATH under repository's root directory because GitLab
  # allows to cache only directories under this.
  GOPATH: $CI_PROJECT_DIR/.go

cache:
  paths:
    - .go/
  key:
    files:
      - go.mod
      - go.sum

build-amd64-linux:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script: GOARCH=amd64 GOOS=linux go build ./
  artifacts:
    name: "linux-amd64-antispam-telegram-bot-$CI_COMMIT_SHORT_SHA-$CI_JOB_ID"
    paths:
      - antispam-telegram-bot
      - README.md
      - LICENSE
    expire_in: 3 day

build-armv7-linux:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script: GOARM=7 GOARCH=arm GOOS=linux go build ./
  artifacts:
    name: "linux-armv7-antispam-telegram-bot-$CI_COMMIT_SHORT_SHA-$CI_JOB_ID"
    paths:
      - antispam-telegram-bot
      - README.md
      - LICENSE
    expire_in: 3 day

vet:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script: go vet ./...
  dependencies: [] # This job doesn't use artifacts!